# Travis-CI Build for DotNetCraft.Extensions
# see travis-ci.org for details

language: csharp
sudo: required
solution: DotNetCraft.Extensions.sln

before_install:
  - export EnableNuGetPackageRestore=true

# Make sure build dependencies are installed.
install:
 - sudo apt-get install -y gtk-sharp2
 - nuget # lets get version number
 - nuget restore DotNetCraft.Extensions.sln -Verbosity detailed
 - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
 
#cache: 
# - apt
# - directories:
#   - packages

# Run the build script
script:
 - xbuild /p:Configuration=Release DotNetCraft.Extensions.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./tests/NinjectDependencyResolver.Tests/bin/Release/NinjectDependencyResolver.Tests.dll

# Only watch the master branch.
branches:
 only:
   - master
